### 实时场景中的自定义独热编码函数

为了处理实时场景中的新类别问题，我们需要自定义独热编码函数。

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
class CustomOneHotEncoder:
    def __init__(self):
        self.class_map = {}
        self.next_class = 0

    def fit_transform(self, X):
        encoded = []
        for item in X:
            if item not in self.class_map:
                self.class_map[item] = self.next_class
                self.next_class += 1
            encoded.append(self.class_map[item])
        return tf.keras.utils.to_categorical(encoded, num_classes=self.next_class)

    def transform(self, X):
        encoded = []
        for item in X:
            if item not in self.class_map:
                self.class_map[item] = self.next_class
                self.next_class += 1
            encoded.append(self.class_map[item])
        return tf.keras.utils.to_categorical(encoded, num_classes=self.next_class)

 `CustomOneHotEncoder` 类：将新类别映射到独热编码中，并保持类别映射的一致性。

### 使用示例

In [3]:
X_train = ['A', 'B', 'C', 'A', 'B']
X_test = ['A', 'C', 'D']

encoder = CustomOneHotEncoder()
X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

print(X_train_encoded)
print(X_test_encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
